import { Cell } from "../board";
import { Piece } from "../piece";

export const makeDefaultState = () => [
  [
    new Cell(new Piece("r", "b", [0, 0]), "w"),
    new Cell(new Piece("n", "b", [0, 1]), "b"),
    new Cell(new Piece("b", "b", [0, 2]), "w"),
    new Cell(new Piece("q", "b", [0, 3]), "b"),
    new Cell(new Piece("k", "b", [0, 4]), "w"),
    new Cell(new Piece("b", "b", [0, 5]), "b"),
    new Cell(new Piece("n", "b", [0, 6]), "w"),
    new Cell(new Piece("r", "b", [0, 7]), "b"),
  ],
  [
    new Cell(new Piece("p", "b", [1, 0]), "b"),
    new Cell(new Piece("p", "b", [1, 1]), "w"),
    new Cell(new Piece("p", "b", [1, 2]), "b"),
    new Cell(new Piece("p", "b", [1, 3]), "w"),
    new Cell(new Piece("p", "b", [1, 4]), "b"),
    new Cell(new Piece("p", "b", [1, 5]), "w"),
    new Cell(new Piece("p", "b", [1, 6]), "b"),
    new Cell(new Piece("p", "b", [1, 7]), "w"),
  ],
  [
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
  ],
  [
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
  ],
  [
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
  ],
  [
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
    new Cell(null, "b"),
    new Cell(null, "w"),
  ],
  [
    new Cell(new Piece("p", "w", [6, 0]), "w"),
    new Cell(new Piece("p", "w", [6, 1]), "b"),
    new Cell(new Piece("p", "w", [6, 2]), "w"),
    new Cell(new Piece("p", "w", [6, 3]), "b"),
    new Cell(new Piece("p", "w", [6, 4]), "w"),
    new Cell(new Piece("p", "w", [6, 5]), "b"),
    new Cell(new Piece("p", "w", [6, 6]), "w"),
    new Cell(new Piece("p", "w", [6, 7]), "b"),
  ],
  [
    new Cell(new Piece("r", "w", [7, 0]), "b"),
    new Cell(new Piece("n", "w", [7, 1]), "w"),
    new Cell(new Piece("b", "w", [7, 2]), "b"),
    new Cell(new Piece("q", "w", [7, 3]), "w"),
    new Cell(new Piece("k", "w", [7, 4]), "b"),
    new Cell(new Piece("b", "w", [7, 5]), "w"),
    new Cell(new Piece("n", "w", [7, 6]), "b"),
    new Cell(new Piece("r", "w", [7, 7]), "w"),
  ],
];
